### PR TITLE
Add explicit typecasting for Booleans, Dates and DateTimes

### LINKED ISSUE #10: `bool` datatype is not properly cast resulting in errors with PostgreSQL
I have taken a first stab at solving this in https://github.com/havok2063/boolean_parser/pull/9.

### PR DESCRIPTION
**Pull request by linozen**
If this isn't done, it leads to errors with PostgreSQL:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function lower(boolean) does not exist
LINE 11: ...wer(person.language) ILIKE '%' || 'de' || '%' AND lower(pers...
                                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

### CODE REVIEW

**Review by havok2063 — COMMENTED** [review]
@linozen Thanks for this PR. It looks good.  Can you add a new test or two for this functionality?  Probably somewhere in `tests/parsers/test_sqla.py`.

**Comment by linozen** [comment]
Hey @havok2063, I now added the same typecasting function for datetimes that I also added for boolean values. This should fix the errors one might encounter when using this package with SQLAlchemy and PostgreSQL as a database engine.

**Comment by linozen** [comment]
Ah, and I added tests to make sure the new typecasting functions work as expected. Let me know if you need anything else before merging this.

Many thanks for your work!

**Review by havok2063 — APPROVED** [review]
This looks good to me.  Nice work.  Thanks a lot for this.

**Pull request merged**
